apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: myapp-php
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      name: mysql
      labels:
        name: mysql
        app: myapp-php
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootroot
