apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    type: front-end
spec:
  replicas: 2
  selector:
    matchLabels:
      name: myapp-php
  template:
    metadata:
      name: php
      labels:
        name: myapp-php
        env: training
    spec:
      imagePullSecrets:
        - name: docker-keys
      containers:
        - image: arulprasath/php-app:latest
          name: php
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASS
              value: rootroot
